In [1]:
import torch

In [4]:
a = torch.rand((2, 3, 4))
a

tensor([[[0.9287, 0.7295, 0.3382, 0.1727],
         [0.5223, 0.2858, 0.9265, 0.5985],
         [0.4457, 0.9788, 0.6885, 0.1604]],

        [[0.3951, 0.6569, 0.5433, 0.1186],
         [0.5852, 0.7568, 0.2620, 0.4211],
         [0.9293, 0.8702, 0.9200, 0.9416]]])

In [6]:
b = torch.rand(3, 4)
b

tensor([[0.4777, 0.9646, 0.7843, 0.7410],
        [0.6550, 0.2704, 0.6395, 0.3912],
        [0.0313, 0.1316, 0.4330, 0.1787]])

In [7]:
c = a + b
c

tensor([[[1.4064, 1.6942, 1.1225, 0.9137],
         [1.1773, 0.5563, 1.5661, 0.9897],
         [0.4770, 1.1104, 1.1215, 0.3391]],

        [[0.8728, 1.6215, 1.3275, 0.8596],
         [1.2401, 1.0272, 0.9015, 0.8124],
         [0.9606, 1.0018, 1.3530, 1.1203]]])

In [8]:
c.shape

torch.Size([2, 3, 4])